version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=habib
    volumes:
      - ./tmp/db/mysql:/var/lib/mysql
  web:
    build:
      context: ./
      dockerfile: web.docker
    command: bash -c "rm -f tmp/pids/server.pid
            && bundle install
            && bundle exec rake db:create
            && bundle exec rake db:migrate
            && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - db
      - redis
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=elasticsearch
      - REDIS_URL=redis://redis:6379

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    hostname: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  redis:
    image: redis
    ports:
      - "6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  worker:
    build:
      context: ./
      dockerfile: web.docker
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/myapp
    links:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=elasticsearch