version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=exampl
    volumes:
      - ./tmp/db:/var/lib/mysql
  web:
    build:
      context: ./
      dockerfile: web.docker
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis
    ports:
      - "6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  worker:
    build:
      context: ./
      dockerfile: web.docker
    command: bundle exec rake environment resque:work QUEUE=*
    volumes:
      - .:/myapp
    links:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  scheduler:
    build:
      context: ./
      dockerfile: web.docker
    command: bundle exec rake environment resque:scheduler
    volumes:
      - .:/myapp
    links:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379